from abc import ABC, abstractmethod
from typing import List, Dict, Any

class InferenceEngine(ABC):
    """Abstract base class for model inference backends.

    Defines the contract for interacting with different inference engines (e.g., vLLM,
    Triton, or local mocks), allowing the API layer to remain agnostic to the underlying
    model serving infrastructure.
    """

    @abstractmethod
    def predict(self, image_base64: str, prompt: str) -> str:
        """Runs inference on a single image.

        Args:
            image_base64: Base64 encoded string of the input image.
            prompt: Text prompt to guide the generation (e.g., "Detect nutrition tables").

        Returns:
            The raw text generated by the model.
        """
        pass

class MockInferenceEngine(InferenceEngine):
    """Mock implementation for testing and development without GPU resources.

    Returns deterministic, valid responses to verify API connectivity and
    post-processing logic.
    """
    def predict(self, image_base64: str, prompt: str) -> str:
        return "nutrition-table<box(100,100),(200,200)>"

class VLLMInferenceEngine(InferenceEngine):
    """vLLM-based inference backend for high-throughput production serving.

    Uses vLLM's PagedAttention kernel to serve Qwen2-VL efficiently.
    (Note: This implementation is a stub as vLLM requires CUDA environment).
    """
    def __init__(self, model_path: str):
        self.model_path = model_path
        self.llm = None
        
    def load(self):
        """Initializes the vLLM engine."""
        # Implementation depends on vLLM API
        # from vllm import LLM, SamplingParams
        # self.llm = LLM(model=self.model_path)
        pass

    def predict(self, image_base64: str, prompt: str) -> str:
        # Implementation would call vLLM generate
        raise NotImplementedError("vLLM integration not fully implemented without GPU environment")
